# CIRCUS CONFIGURATION v1

# This configuration file uses YAML for its syntax.
# Indentation is meaningful in YAML. Make sure that you use spaces, rather than
# tab characters, to indent sections. Modifing indentation of config structure
# may cause unexpected problems. If you need to specify some special characters
# such as colon or braces, it's a good idea to wrap values in quotation marks.

# bucket [required]
# The name of your Amazon S3 bucket which should be mounted.
#
bucket: examplebucket

# region [optional]
# The name of AWS Region where your Amazon S3 bucket is located.
# If not specified, Circus will automatically detect the location of you bucket.
#
#region: us-east-1

# access_key_id [optional]
# The AWS access key ID which is required to access your AWS resources.
# If not specified, the default credential profiles file (typically located at
# ~/.aws/credentials) or Amazon EC2 instance profile credentials will be used.
#
#access_key_id: AKIAIOSFODNN7EXAMPLE

# secret_access_key [optional]
# The AWS secret access key which is required to access your AWS resources.
# If not specified, the default credential profiles file (typically located at
# ~/.aws/credentials) or Amazon EC2 instance profile credentials will be used.
#
#secret_access_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

# log_output [optional]
# The path to the file where errors should be logged. If the special value
# "STDOUT" or "STDERR" is used, the errors are sent to stdout or stderr instead.
# The special value "NONE" can be used to disable logging (This is default).
#
#log_output: STDERR

# log_level [optional]
# The severity threshold of logging. You can give one of the following levels:
# "FATAL", "ERROR", "WARN", "INFO", and "DEBUG". Only messages at that level or
# higher will be logged. The default level is "WARN".
#
#log_level: DEBUG

# cache_driver [optional]
# Select cache driver you would like to be used for caching objects' attributes.
# By default, Circus is configured to use the "memory_store" cache driver.
# - "file_store":         uses the local file system to store data.
# - "memory_store":       keeps data in memory in the same Circus process.
# - "mem_cache_store":    uses memcached server to provide a centralized cache.
#
#cache_driver: memory_store

# cache_ttl [optional]
# The number of seconds for which objects' attributes should be cached. This
# value must be larger than zero. The default value is 300 (5 minutes).
#
#cache_ttl: 300

# The configuration options for file_store cache driver.
# directory = The path to the directory where the store files will be stored.
#
file_store:
  directory: /tmp/cache

# The configuration options for memory_store cache driver.
# size = The bounded size (in megabytes) of the cache store.
#
memory_store:
  size: 32

# The configuration options for mem_cache_store cache driver.
# servers = The addresses for all memcached servers in your cluster.
#
mem_cache_store:
  servers: [ 'localhost:11211' ]
